In [1]:
import numpy as np

In [9]:
my_arr = np.arange(1000000)

In [13]:
my_list = list(range(1000000))

In [14]:
%time for _ in range(10): my_arr2 = my_arr * 2

Wall time: 46 ms


In [15]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 1.65 s


In [16]:
my_arr3 = np.random.randn(2,3)

In [18]:
my_arr3

array([[ 0.19802263, -1.06149823,  0.35691862],
       [ 1.93807596,  0.25912473, -0.21186259]])

In [22]:
my_arr4 = np.append(my_arr3,2)
my_arr4

array([ 0.19802263, -1.06149823,  0.35691862,  1.93807596,  0.25912473,
       -0.21186259,  2.        ])

In [23]:
data = my_arr3 * 5

In [24]:
data

array([[ 0.99011315, -5.30749115,  1.78459309],
       [ 9.69037982,  1.29562363, -1.05931297]])

In [26]:

data.ndim

2

In [28]:
data.dtype

dtype('float64')

In [29]:
data.shape

(2, 3)

In [36]:
ass =  np.zeros(2)

In [38]:
ass.ndim

1

In [39]:
ass2 = np.zeros((2,3))

In [40]:
ass2.ndim

2

In [53]:
ass3 = np.zeros((2,3,3))
ass3

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [55]:
ass3.ndim

3

In [50]:
ass4 = np.zeros((3,2,3,4))
ass4

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [49]:
ass4.ndim

4

In [76]:
myarr = ([[[0,0,0,0],[0,0,0,0],[1,1,1,1],[1,1,1,1]]])
myarr1 = np.array(myarr)
myarr1

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [77]:
myarr1.ndim

3

In [78]:
myarr1.shape

(1, 4, 4)

In [82]:
np.empty((2,2,2))

array([[[0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 5.90902512e-321],
        [9.34600962e-307, 2.56761491e-312]]])

In [87]:
a = ([2,2],[2,2])
arr = np.asarray(a)
arr

array([[2, 2],
       [2, 2]])

In [88]:
arr1 = arr.copy

In [104]:
arr11 = np.ones((2,2), dtype = 'int16' ) #int8,int16,int32,int64,int128 or unsigned uint8,uint16 and so on....
arr11

array([[1, 1],
       [1, 1]], dtype=int16)

In [103]:
arr11 = np.ones((2,2), dtype = 'float64' ) # float16,float32,float64,128
arr11

array([[1., 1.],
       [1., 1.]])

In [105]:
arr11 = np.ones((2,2), dtype = 'complex64' ) #complex64,128,256
arr11

array([[1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j]], dtype=complex64)

In [106]:
arr11 = np.ones((2,2), dtype = 'string_' )
arr11

array([[b'1', b'1'],
       [b'1', b'1']], dtype='|S1')

In [107]:
arr11 = np.ones((2,2), dtype = 'unicode_' )
arr11

array([['1', '1'],
       ['1', '1']], dtype='<U1')

In [108]:
arr11 = np.ones((2,2), dtype = 'object' )
arr11

array([[1, 1],
       [1, 1]], dtype=object)

In [112]:
arr12 = np.ones_like(arr11)
arr12

array([[1, 1],
       [1, 1]], dtype=object)

In [114]:
arr13 = np.ones_like(arr)
arr

array([[2, 2],
       [2, 2]])

In [118]:
arr14 = np.full((2,2),12)
arr14

array([[12, 12],
       [12, 12]])

In [123]:
arr15 = np.full_like(arr14,11)
arr15

array([[11, 11],
       [11, 11]])

In [124]:
arr111 = np.random.randn(3,3)

In [129]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [131]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [135]:
np.empty((2,2), dtype = 'int64')

array([[4607182418800017408,                   0],
       [                  0, 4607182418800017408]], dtype=int64)

In [141]:
arr = np.array([[2,2],[1,4]])
arr

array([[2, 2],
       [1, 4]])

In [153]:
arr += arr
arr

array([[nan, nan],
       [nan, nan]])

In [145]:
arr -= arr
arr

array([[0, 0],
       [0, 0]])

In [147]:
arr *= arr
arr

array([[0, 0],
       [0, 0]])

In [151]:
arr = arr / arr
arr

array([[nan, nan],
       [nan, nan]])

In [154]:
arr ** 0.5
arr

array([[nan, nan],
       [nan, nan]])

In [157]:
arr12 > arr11

array([[False, False],
       [False, False]])